<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>book_category</name>
   <tag></tag>
   <elementGuidId>df230189-7f48-4cff-ba0b-9379bef4c128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div/div/div[2]/div/div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div/div/div[2]/div/div[6]</value>
      <webElementGuid>59b34052-10b9-4637-8740-ed8040d3d502</webElementGuid>
   </webElementProperties>
</WebElementEntity>
