<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>book_store_app</name>
   <tag></tag>
   <elementGuidId>af17a40f-2072-44b6-8f59-9e672b86718a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/div/div/div/div[1]/div/div/div[6]/span/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/div/div/div/div[1]/div/div/div[6]/span/div/div[1]</value>
      <webElementGuid>30aff5bb-9940-4307-aa22-8a9c72013106</webElementGuid>
   </webElementProperties>
</WebElementEntity>
