<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alert_invalid_login</name>
   <tag></tag>
   <elementGuidId>9daf8c23-bf44-458c-a65a-24bb69cbc417</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;name&quot;]</value>
      <webElementGuid>eb8c36ad-068a-402d-87c6-32ec823b8957</webElementGuid>
   </webElementProperties>
</WebElementEntity>
