<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login_menu</name>
   <tag></tag>
   <elementGuidId>0f3ede98-ace3-4fd9-85b8-927c7679e217</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div/div/div[1]/div/div/div[6]/div/ul/li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div/div/div[1]/div/div/div[6]/div/ul/li[1]</value>
      <webElementGuid>6d29d4fd-f219-41a6-a29a-c3ce6c3f12b7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
