<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login_menu</name>
   <tag></tag>
   <elementGuidId>17206bdc-3415-4a3c-8df6-38bf5269d4aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div/div/div[1]/div/div/div[6]/div/ul/li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div/div/div[1]/div/div/div[6]/div/ul/li[1]</value>
      <webElementGuid>a06cb649-b649-49f9-889f-20aac060b010</webElementGuid>
   </webElementProperties>
</WebElementEntity>
