<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login_page</name>
   <tag></tag>
   <elementGuidId>2e71fdc7-76a5-4142-98a5-8b0f9b26c2a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;userForm&quot;]/div[1]/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;userForm&quot;]/div[1]/h2</value>
      <webElementGuid>ee51240a-efaf-4715-a37d-588f8f205214</webElementGuid>
   </webElementProperties>
</WebElementEntity>
